on:
  push:
    branches:
      - main

# This 'jobs:' block is just for context of where 'steps:' lives
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # ... other job-level settings like defaults ...
    steps:
      # ... your previous steps (checkout, setup-node, npm ci, npm run build) ...

      # THE DEPLOY STEP:
      - name: Deploy to Firebase                # Step starts here. Let's call this Indentation Level 0 for the step.
        uses: FirebaseExtended/action-hosting-deploy@v0 # Same Indentation Level 0
        with:                                   # Same Indentation Level 0
          repoToken: '${{ secrets.GITHUB_TOKEN }}' # Indented further (child of 'with')
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_YOUR_PROJECT_NAME }}' # Indented further
          projectId: gemma-garage                 # Indented further
          # channelId: live                     # Indented further (commented out)
        working-directory: ./source/frontend/llm-garage-frontend # Same Indentation Level 0